# Official Node.js image that includes Python
FROM node:20-bullseye AS base
WORKDIR /app

# Install system dependencies
RUN apt-get update && apt-get install -y \
    gdal-bin \
    libgdal-dev \
    libexpat1 \
    gcc \
    g++ \
    python3-dev \
    python3-pip \
    netcat-traditional \
    && npm install -g pnpm \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# Set GDAL environment variables
ENV CPLUS_INCLUDE_PATH=/usr/include/gdal \
    C_INCLUDE_PATH=/usr/include/gdal

# Install backend dependencies
COPY monbo-api/requirements.txt /app/backend/
RUN cd /app/backend && pip install --no-cache-dir -r requirements.txt

# Install frontend dependencies
COPY monbo-front/package.json monbo-front/pnpm-lock.yaml /app/frontend/
RUN cd /app/frontend && pnpm install --frozen-lockfile

# Copy entrypoint
COPY /entrypoint.dev.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

EXPOSE 3000 8000
ENTRYPOINT ["/entrypoint.sh"]