export const GOOGLE_SERVICE_API_KEY =
  process.env.NEXT_PUBLIC_GOOGLE_SERVICE_API_KEY || "";

export const GET_MAPS_URL = process.env.NEXT_PUBLIC_GET_MAPS_URL || "";

export const POLYGON_VALIDATION_PARSER_URL =
  process.env.NEXT_PUBLIC_POLYGON_VALIDATION_PARSER_URL || "";

export const POLYGON_VALIDATION_URL =
  process.env.NEXT_PUBLIC_POLYGON_VALIDATION_URL || "";

export const DEFORESTATION_ANALYSIS_PARSER_URL =
  process.env.NEXT_PUBLIC_DEFORESTATION_ANALYSIS_PARSER_URL || "";

export const DEFORESTATION_ANALYSIS_URL =
  process.env.NEXT_PUBLIC_DEFORESTATION_ANALYSIS_URL || "";

export const DEFORESTATION_ANALYSIS_TILES_URL =
  process.env.NEXT_PUBLIC_DEFORESTATION_ANALYSIS_TILES_URL || "";
