"use client";

import { Box, alpha, useTheme } from "@mui/material";
import countryShapes from "@/utils/countryShapes.json";
import { countries } from "@/utils/countries";

// Silhouettes fitted to a 100×100 box, keyed by ISO 3166-1 numeric code
// (generated by scripts/generate-country-shapes.mjs).
const shapes: Record<string, string> = countryShapes;

const shapeOf = (code: string) => {
  const numericCode = countries.find((c) => c.code === code)?.numericCode;
  return numericCode ? shapes[numericCode] : undefined;
};

interface CountryCardProps {
  code: string;
  name: string;
  selected: boolean;
  onSelect: (code: string) => void;
}

/** A square card with the country's silhouette behind its name. */
export const CountryCard: React.FC<CountryCardProps> = ({
  code,
  name,
  selected,
  onSelect,
}) => {
  const colors = useTheme().palette.landing;
  const shape = shapeOf(code);

  return (
    <Box
      component="button"
      type="button"
      aria-pressed={selected}
      onClick={() => onSelect(code)}
      sx={{
        position: "relative",
        aspectRatio: "1 / 1",
        border: 0,
        borderRadius: "24px",
        backgroundColor: selected ? colors.primary : colors.tint,
        color: selected ? "#fff" : colors.primary,
        font: "inherit",
        cursor: "pointer",
        overflow: "hidden",
        display: "grid",
        placeItems: "center",
        boxShadow: "0 1px 3px rgba(0,0,0,.05)",
        transition: "background-color .18s, transform .18s, box-shadow .18s",
        "&:hover": selected
          ? {}
          : {
              backgroundColor: colors.tintHover,
              transform: "translateY(-2px)",
              boxShadow: `0 6px 18px ${alpha(colors.primary, 0.12)}`,
            },
        "&:focus-visible": {
          outline: `3px solid ${colors.primaryDark}`,
          outlineOffset: 3,
        },
      }}
    >
      {shape && (
        <Box
          component="svg"
          viewBox="0 0 100 100"
          aria-hidden
          sx={{
            position: "absolute",
            inset: "10%",
            width: "80%",
            height: "80%",
            "& path": {
              fill: selected ? colors.shapeSelected : colors.shape,
              transition: "fill .18s",
            },
          }}
        >
          <path d={shape} />
        </Box>
      )}
      <Box
        component="span"
        sx={{
          position: "relative",
          fontSize: { xs: 28, md: 34 },
          fontWeight: 700,
          letterSpacing: "-.01em",
          padding: 1,
        }}
      >
        {name}
      </Box>
      <Box
        component="span"
        aria-hidden
        sx={{
          position: "absolute",
          top: 18,
          right: 18,
          width: 26,
          height: 26,
          borderRadius: "50%",
          border: `2px solid ${selected ? "#fff" : colors.ring}`,
          backgroundColor: selected ? "#fff" : "rgba(255,255,255,.6)",
          display: "grid",
          placeItems: "center",
          "&::after": selected
            ? {
                content: '""',
                width: 12,
                height: 12,
                borderRadius: "50%",
                backgroundColor: colors.primary,
              }
            : {},
        }}
      />
    </Box>
  );
};
