/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Root
         * @description Root endpoint that serves the API status page.
         *     Returns an HTML page with a spinning gear animation indicating the API is running.
         *     If the template file is not found, returns a simple fallback HTML response.
         *
         *     Returns:
         *         Response: HTML content with status page
         */
        get: operations["root__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/jobs/{job_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Job
         * @description Status of an ingestion job of the session's country: queued, running,
         *     succeeded, failed or cancelled, with the phase and progress while running.
         */
        get: operations["get_job_admin_jobs__job_id__get"];
        put?: never;
        post?: never;
        /**
         * Cancel Job
         * @description Cancel a queued or running job of the session's country. A 202 guarantees the
         *     layer keeps its raster; the job reports `cancelled` once it stops (at the
         *     latest when a running conversion returns). 409 when the job has ended or its
         *     activation has begun.
         */
        delete: operations["cancel_job_admin_jobs__job_id__delete"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Layers
         * @description Every layer of the session's country, enabled or not, with its metadata in
         *     every language.
         */
        get: operations["list_layers_admin_layers_get"];
        put?: never;
        /**
         * Create Layer
         * @description Create a layer in the session's country. It starts disabled and without a
         *     raster; upload one and then enable the layer to publish it. Its id is one more
         *     than the highest id in the country (disabled layers included), so ids are never
         *     reused.
         */
        post: operations["create_layer_admin_layers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/layers/{layer_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Update Layer
         * @description Replace a layer's editable fields and its metadata in every language. The id,
         *     raster, version, enabled state and country are not changed here.
         */
        put: operations["update_layer_admin_layers__layer_id__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /**
         * Set Layer Enabled
         * @description Publish (enable) or hide (disable) a layer. A hidden layer disappears from the
         *     public listing but still resolves by id for analyses and tiles. A layer can
         *     only be enabled once it has a raster.
         */
        patch: operations["set_layer_enabled_admin_layers__layer_id__patch"];
        trace?: never;
    };
    "/admin/layers/{layer_id}/raster": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /**
         * Upload Raster
         * @description Upload a GeoTIFF for a layer as the raw request body (not multipart). It is
         *     validated, converted to a Cloud Optimized GeoTIFF and activated in the
         *     background; poll `GET /admin/jobs/{jobId}` for the result, or cancel it with
         *     `DELETE /admin/jobs/{jobId}`. The layer keeps its current raster until the job
         *     succeeds. Only one upload is processed at a time, across every country.
         */
        put: operations["upload_raster_admin_layers__layer_id__raster_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/admin/session": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Session
         * @description Check that the current token is still valid, when it expires and which
         *     country it administers.
         */
        get: operations["get_session_admin_session_get"];
        put?: never;
        /**
         * Create Session
         * @description Exchange a country's admin passkey for a session token that administers that
         *     country (returned as `country`).
         *
         *     Send the token back as `Authorization: Bearer <token>` on every admin call. After
         *     5 failed attempts from the same IP within 15 minutes, logins from that IP get
         *     429 (even with the right passkey) until the window passes.
         */
        post: operations["create_session_admin_session_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Config
         * @description Product settings the frontend needs, owned by the API's environment so there is a
         *     single place to set them. The frontend loads them once at startup.
         */
        get: operations["get_config_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/countries": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Countries
         * @description The countries a visitor can analyze: enabled in the country registry and with
         *     at least one enabled layer, sorted by ISO 3166-1 alpha-2 code. With the legacy
         *     flat layout, the countries listed by the enabled layers.
         */
        get: operations["get_countries_countries_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deforestation_analysis/analize": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Analize */
        post: operations["analize_deforestation_analysis_analize_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deforestation_analysis/generate-image": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Image */
        post: operations["generate_image_deforestation_analysis_generate_image_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/deforestation_analysis/tiles/{country}/{map_id}/dynamic/{z}/{x}/{y}.png": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Serve Tile
         * @description Serve a tile of a country's layer for the specified z/x/y.
         */
        get: operations["serve_tile_deforestation_analysis_tiles__country___map_id__dynamic__z___x___y__png_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/download-geojson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Download Geojson */
        get: operations["download_geojson_download_geojson_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/farms/parse": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Parse Farms
         * @description Endpoint to parse farm data and generate polygon information.
         *
         *     Args:
         *         body (list[InputFarmData]): List of unprocessed farm data
         *         locale (str): Locale for number parsing, either 'en' or 'es'. Defaults to 'en'
         *
         *     Returns:
         *         list[FarmData]: List of processed farm data with polygon information
         *
         *     Raises:
         *         HTTPException: If there is an error in:
         *             - Parsing farm coordinates
         *             - Generating polygons
         *             - Invalid locale format
         *             - Invalid number formats for the given locale
         *             - Invalid country codes
         *             - Invalid document URLs
         *             - Duplicate farm IDs (if IDs are provided)
         *
         *     The endpoint performs the following steps:
         *     1. Validates the locale and farm data inputs
         *     2. Parses and validates all numeric values according to the locale
         *     3. Validates country codes, coordinates format, and document URLs
         *     4. Generates polygon information based on the parsed coordinates
         *     5. Auto-generates IDs if needed:
         *        - If all farms are missing IDs, sequential numbers are assigned
         *        - If some farms have IDs, IDs matching the existing pattern are generated for
         *        those missing IDs
         *        - If all farms have IDs, no changes are made
         *
         *     Each farm data includes:
         *     - Basic information such as id, producer, crop type, production details, etc.
         *     - Polygon type (either "polygon" or "point")
         *     - Polygon details including coordinates, area and other geometric properties
         */
        post: operations["parse_farms_farms_parse_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health Check */
        get: operations["health_check_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness Check */
        get: operations["liveness_check_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/maps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Maps
         * @description Retrieve the enabled maps with their metadata and attributes.
         *
         *     This endpoint reads the maps index file and their corresponding metadata
         *     files to return detailed information about each enabled map layer. Disabled
         *     layers are left out here but remain usable by id for analysis and tiles.
         *
         *     Args:
         *         language (str, optional): Language code for the metadata. Defaults to "en".
         *         country (str, optional): ISO 3166-1 alpha-2 code: only that country's
         *             layers (an empty list for a country that is unknown or disabled).
         *             Without it, the layers of every enabled country.
         *
         *     Returns:
         *         list[BaseMapData]: A list of maps with the following attributes:
         *         - id: The layer's id within its country (with the legacy flat layout,
         *           unique on its own). Analysis, tiles and image generation take it with
         *           the country
         *         - name: Complete name of the layer (e.g., "Global Forest Watch")
         *         - alias: Short name or reference (e.g., "GFW 2020-2023")
         *         - baseline: Base year for comparison
         *         - comparedAgainst: Final year for comparison
         *         - coverage: Geographic coverage of the layer
         *         - source: Origin of the layer data
         *         - resolution: Spatial resolution (e.g., "30 x 30 meters")
         *         - contentDate: Period covered by the data
         *         - updateFrequency: How often the data is updated
         *         - publishDate: When the map data was published/released
         *         - references: Reference URLs for the data source
         *         - considerations: Special considerations and notes about the layer
         *           (in Markdown format)
         *         - country: The layer's country (None in the legacy flat layout). Ids are
         *           numbered within each country, so country and id identify a layer.
         *         - availableCountriesCodes: The layer's country, as a one-element list of
         *           ISO 3166-1 alpha-2 codes (in the legacy flat layout, every country the
         *           layer lists)
         *         - version: Raster version, incremented on every raster replacement (the
         *           frontend appends it to tile URLs to bypass cached tiles)
         *         - pixelSize: Nominal pixel size in meters, used by the analysis formula
         */
        get: operations["get_maps_maps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/polygons_validation/validate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Validate Polygons
         * @description Validates a list of farm polygons by checking for overlaps and geometry
         *     inconsistencies.
         *
         *     Args:
         *         body (list[FarmPolygon]): List of farm polygons to validate.
         *
         *     Returns:
         *         PolygonInconsistenciesResponse: A response object containing:
         *             - farmResults (list[FarmResult]): A list of validation results
         *               for each farm, with status either "VALID" or "NOT_VALID"
         *             - inconsistencies (list[PolygonInconsistency]): A list of detected
         *               inconsistencies, which can be overlaps or geometry issues
         *
         *     The function performs the following validations:
         *     1. Converts the input FarmPolygons into Shapely geometry objects
         *     2. Checks for overlapping polygons between farms
         *     3. Validates the geometry of each polygon (e.g. self-intersections)
         *     4. Marks farms as "NOT_VALID" if they are involved in any inconsistency
         */
        post: operations["Validate_Polygons_polygons_validation_validate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AdminLayer */
        AdminLayer: {
            /** Attributes */
            attributes: {
                [key: string]: components["schemas"]["StoredAttributes"] | null;
            };
            /** Baseline */
            baseline: number | null;
            /** Compared Against */
            compared_against: number | null;
            /** Considerations */
            considerations: {
                [key: string]: string | null;
            };
            /** Enabled */
            enabled: boolean;
            /** Has Raster */
            has_raster: boolean;
            /** Id */
            id: number;
            /** Pixel Size */
            pixel_size: number;
            /** Raster Filename */
            raster_filename: string | null;
            /** References */
            references: string[];
            /** Version */
            version: number;
        };
        /** AnalizeBody */
        AnalizeBody: {
            /** Country */
            country?: string | null;
            /** Farms */
            farms: components["schemas"]["FarmPolygonDetailData"][];
            /** Maps */
            maps: number[];
        };
        /** BaseMapData */
        BaseMapData: {
            /** Alias */
            alias: string | null;
            /** Availablecountriescodes */
            availableCountriesCodes: string[];
            /** Baseline */
            baseline: number | null;
            /** Comparedagainst */
            comparedAgainst: number | null;
            /** Considerations */
            considerations: string | null;
            /** Contentdate */
            contentDate: string | null;
            /** Country */
            country: string | null;
            /** Coverage */
            coverage: string | null;
            /** Id */
            id: number;
            /** Name */
            name: string | null;
            /** Pixelsize */
            pixelSize: number;
            /** Publishdate */
            publishDate: string | null;
            /** References */
            references: string[];
            /** Resolution */
            resolution: string | null;
            /** Source */
            source: string | null;
            /** Updatefrequency */
            updateFrequency: string | null;
            /** Version */
            version: number;
        };
        /** ConfigData */
        ConfigData: {
            /** Deforestationthresholdpercentage */
            deforestationThresholdPercentage: number;
            /** Overlapthresholdpercentage */
            overlapThresholdPercentage: number;
        };
        /** Coordinates */
        Coordinates: {
            /** Lat */
            lat: number;
            /** Lng */
            lng: number;
        };
        /** CountryData */
        CountryData: {
            /** Code */
            code: string;
        };
        /** Document */
        Document: {
            /** Name */
            name: string;
            /** Url */
            url: string;
        };
        /** EmptyPolygonInconsistency */
        EmptyPolygonInconsistency: {
            /** Data */
            data: null;
            /** Farmids */
            farmIds: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "empty_polygon";
        };
        /**
         * EnabledInput
         * @description Body of `PATCH /admin/layers/{id}`.
         */
        EnabledInput: {
            /** Enabled */
            enabled: boolean;
        };
        /** FarmData */
        FarmData: {
            /** Association */
            association: string | null;
            /** Country */
            country: string;
            /** Croptype */
            cropType: string;
            /** Documents */
            documents: components["schemas"]["Document"][];
            /** Id */
            id: string;
            /** Polygon */
            polygon: components["schemas"]["PointSummary"] | components["schemas"]["PolygonShapeSummary"];
            /** Producer */
            producer: string;
            /** Producerid */
            producerId: string;
            /** Production */
            production: number;
            /** Productiondate */
            productionDate: string;
            /** Productionquantityunit */
            productionQuantityUnit: string;
            /** Region */
            region: string | null;
        };
        /** FarmDeforestation */
        FarmDeforestation: {
            /** Farmid */
            farmId: string;
            /** Value */
            value: number | null;
        };
        /** FarmPolygonDetailData */
        FarmPolygonDetailData: {
            /** Details */
            details: components["schemas"]["PolygonDetails"] | components["schemas"]["PointDetails"] | null;
            /** Id */
            id: string;
            /**
             * Type
             * @enum {string}
             */
            type: "polygon" | "point";
        };
        /** FarmResult */
        FarmResult: {
            /** Farmid */
            farmId: string;
            /**
             * Status
             * @enum {string}
             */
            status: "VALID" | "VALID_MANUALLY" | "NOT_VALID";
        };
        /** GenerateImageBody */
        GenerateImageBody: {
            /** Country */
            country?: string | null;
            /** Feature */
            feature: {
                [key: string]: unknown;
            };
            /** Mapid */
            mapId: number;
            /** Version */
            version?: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IngestionJob
         * @description An ingestion job as `GET /admin/jobs/{jobId}` returns it. Fields that jobs
         *     saved by earlier releases may lack default to null.
         */
        IngestionJob: {
            /** Country */
            country: string;
            /** Createdat */
            createdAt: string;
            error: components["schemas"]["JobIssue"] | null;
            /** Jobid */
            jobId: string;
            /** Layerid */
            layerId: number;
            /** Phase */
            phase: ("validating" | "converting") | null;
            /** Progress */
            progress: number | null;
            /** Rasterfilename */
            rasterFilename: string | null;
            report: components["schemas"]["RasterReport"] | null;
            /** Requestednodata */
            requestedNodata: number | null;
            /**
             * Status
             * @enum {string}
             */
            status: "queued" | "running" | "succeeded" | "failed" | "cancelled";
            /** Updatedat */
            updatedAt: string;
            /** Version */
            version: number | null;
            /** Warnings */
            warnings: components["schemas"]["JobIssue"][];
        };
        /** InputFarmData */
        InputFarmData: {
            /** Area */
            area?: number | string | null;
            /** Association */
            association?: string | null;
            /**
             * Coordinatesformat
             * @enum {string}
             */
            coordinatesFormat: "WKT" | "GeoJSON";
            /** Country */
            country: string;
            /** Croptype */
            cropType: string;
            /** Documents */
            documents: components["schemas"]["Document"][];
            /** Farmcoordinates */
            farmCoordinates: string;
            /**
             * Geometrytype
             * @enum {string}
             */
            geometryType: "Point" | "Polygon";
            /** Id */
            id?: string | number | null;
            /** Producername */
            producerName: string;
            /** Productiondate */
            productionDate: string;
            /** Productionquantity */
            productionQuantity: number | string;
            /** Productionquantityunit */
            productionQuantityUnit: string;
            /** Region */
            region?: string | null;
        };
        /** InvalidGeometryInconsistency */
        InvalidGeometryInconsistency: {
            data: components["schemas"]["InvalidGeometryInconsistencyData"];
            /** Farmids */
            farmIds: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "invalid_geometry";
        };
        /** InvalidGeometryInconsistencyData */
        InvalidGeometryInconsistencyData: {
            /** Reason */
            reason: string;
        };
        /** JobAccepted */
        JobAccepted: {
            /** Jobid */
            jobId: string;
        };
        /** JobCancelled */
        JobCancelled: {
            /**
             * Cancelled
             * @constant
             */
            cancelled: true;
            /** Jobid */
            jobId: string;
        };
        /**
         * JobIssue
         * @description An error or warning with a stable code; the UI translates it by code.
         */
        JobIssue: {
            /** Code */
            code: string;
            /** Message */
            message: string;
            /** Params */
            params: {
                [key: string]: unknown;
            };
        };
        /**
         * LayerAttributes
         * @description What `metadata/attributes/<lang>/*.json` holds for one language.
         */
        LayerAttributes: {
            /** Alias */
            alias: string;
            /** Contentdate */
            contentDate?: string | null;
            /** Coverage */
            coverage?: string | null;
            /** Name */
            name: string;
            /** Publishdate */
            publishDate?: string | null;
            /** Resolution */
            resolution?: string | null;
            /** Source */
            source?: string | null;
            /** Updatefrequency */
            updateFrequency?: string | null;
        };
        /**
         * LayerInput
         * @description Body of `POST /admin/layers` and `PUT /admin/layers/{id}`.
         */
        LayerInput: {
            attributes: components["schemas"]["LocalizedAttributes"];
            /** Baseline */
            baseline: number;
            /** Compared Against */
            compared_against: number;
            considerations?: components["schemas"]["LocalizedConsiderations"];
            /**
             * Pixel Size
             * @description Pixel size in meters
             */
            pixel_size: number;
            /** References */
            references?: string[];
        };
        /** LocalizedAttributes */
        LocalizedAttributes: {
            en: components["schemas"]["LayerAttributes"];
            es: components["schemas"]["LayerAttributes"];
        };
        /**
         * LocalizedConsiderations
         * @description Markdown per language; empty or missing means no considerations.
         */
        LocalizedConsiderations: {
            /** En */
            en?: string | null;
            /** Es */
            es?: string | null;
        };
        /** LoginBody */
        LoginBody: {
            /** Passkey */
            passkey: string;
        };
        /** MapData */
        MapData: {
            /** Farmresults */
            farmResults: components["schemas"]["FarmDeforestation"][];
            /** Mapid */
            mapId: number;
            /** Version */
            version: number;
        };
        /** OverlapData */
        OverlapData: {
            /** Area */
            area: number;
            center: components["schemas"]["Coordinates"];
            /**
             * Criticality
             * @enum {string}
             */
            criticality: "HIGH" | "MEDIUM";
            /** Paths */
            paths: components["schemas"]["Coordinates"][][];
            /** Percentage */
            percentage: number;
        };
        /** OverlapInconsistency */
        OverlapInconsistency: {
            data: components["schemas"]["OverlapData"];
            /** Farmids */
            farmIds: string[];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "overlap";
        };
        /** PointDetails */
        PointDetails: {
            center: components["schemas"]["Coordinates"];
            /** Radius */
            radius: number;
        };
        /**
         * PointSummary
         * @description A farm given as a point: always a center, a radius and the area they cover.
         */
        PointSummary: {
            /** Area */
            area: number;
            details: components["schemas"]["PointDetails"];
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "point";
        };
        /** PolygonDetails */
        PolygonDetails: {
            center: components["schemas"]["Coordinates"];
            /** Path */
            path: components["schemas"]["Coordinates"][];
        };
        /** PolygonInconsistenciesResponse */
        PolygonInconsistenciesResponse: {
            /** Farmresults */
            farmResults: components["schemas"]["FarmResult"][];
            /** Inconsistencies */
            inconsistencies: (components["schemas"]["OverlapInconsistency"] | components["schemas"]["InvalidGeometryInconsistency"] | components["schemas"]["EmptyPolygonInconsistency"])[];
        };
        /**
         * PolygonShapeSummary
         * @description A farm given as a polygon; details and area are null when the geometry is
         *     empty.
         */
        PolygonShapeSummary: {
            /** Area */
            area: number | null;
            details: components["schemas"]["PolygonDetails"] | null;
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            type: "polygon";
        };
        /** RasterReport */
        RasterReport: {
            /** Approxresolutionm */
            approxResolutionM: number | null;
            /** Bounds */
            bounds: number[];
            /** Crs */
            crs: string;
            /** Dtype */
            dtype: string;
            /** Height */
            height: number;
            /** Nodata */
            nodata: number | null;
            /** Values */
            values: number[];
            /** Width */
            width: number;
        };
        /** SessionData */
        SessionData: {
            /** Country */
            country: string;
            /** Expiresat */
            expiresAt: string;
            /** Token */
            token: string;
        };
        /** SessionStatus */
        SessionStatus: {
            /** Country */
            country: string;
            /** Expiresat */
            expiresAt: string;
        };
        /**
         * StoredAttributes
         * @description Attributes as found on disk; lenient, since older files may lack fields.
         */
        StoredAttributes: {
            /** Alias */
            alias: string | null;
            /** Contentdate */
            contentDate: string | null;
            /** Coverage */
            coverage: string | null;
            /** Name */
            name: string | null;
            /** Publishdate */
            publishDate: string | null;
            /** Resolution */
            resolution: string | null;
            /** Source */
            source: string | null;
            /** Updatefrequency */
            updateFrequency: string | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    root__get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_job_admin_jobs__job_id__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["IngestionJob"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    cancel_job_admin_jobs__job_id__delete: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                job_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobCancelled"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_layers_admin_layers_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLayer"][];
                };
            };
        };
    };
    create_layer_admin_layers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLayer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_layer_admin_layers__layer_id__put: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LayerInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLayer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_layer_enabled_admin_layers__layer_id__patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EnabledInput"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AdminLayer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    upload_raster_admin_layers__layer_id__raster_put: {
        parameters: {
            query?: {
                /** @description Nodata value, for rasters whose file doesn't declare one */
                nodata?: number | null;
            };
            header?: never;
            path: {
                layer_id: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            202: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["JobAccepted"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_session_admin_session_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionStatus"];
                };
            };
        };
    };
    create_session_admin_session_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SessionData"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_config_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConfigData"];
                };
            };
        };
    };
    get_countries_countries_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CountryData"][];
                };
            };
        };
    };
    analize_deforestation_analysis_analize_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AnalizeBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MapData"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    generate_image_deforestation_analysis_generate_image_post: {
        parameters: {
            query?: {
                /** @description Whether to include satellite imagery as background */
                include_satelital_background?: boolean;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateImageBody"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    serve_tile_deforestation_analysis_tiles__country___map_id__dynamic__z___x___y__png_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                country: string;
                map_id: number;
                z: number;
                x: number;
                y: number;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    download_geojson_download_geojson_get: {
        parameters: {
            query?: {
                content?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    parse_farms_farms_parse_post: {
        parameters: {
            query?: {
                /** @description Locale for number parsing, e.g., 'en' or 'es' */
                locale?: string;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["InputFarmData"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmData"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_check_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    liveness_check_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    get_maps_maps_get: {
        parameters: {
            query?: {
                language?: string;
                country?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["BaseMapData"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    Validate_Polygons_polygons_validation_validate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmPolygonDetailData"][];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PolygonInconsistenciesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
