FROM node:20-alpine as frontend-runner
WORKDIR /app

# Install development dependencies
RUN npm install -g pnpm

# Copy package files for dependency installation
COPY package*.json pnpm-lock.yaml ./
RUN pnpm install

# Set environment variables
ENV NEXT_TELEMETRY_DISABLED=1
ENV NODE_ENV=development
# Variables for better performance
ENV WATCHPACK_POLLING=true
ENV CHOKIDAR_USEPOLLING=true
ENV NEXT_WEBPACK_USEPOLLING=1

# Expose development port
EXPOSE 3000

# Start development server with hot-reloading
CMD ["pnpm", "run", "dev"]