interface Country {
  code: string;
  nameEn: string;
  nameEs: string;
}

export const countries: Country[] = [
  { code: "AD", nameEn: "Andorra", nameEs: "Andorra" },
  {
    code: "AE",
    nameEn: "United Arab Emirates",
    nameEs: "Emiratos Árabes Unidos",
  },
  { code: "AF", nameEn: "Afghanistan", nameEs: "Afganistán" },
  { code: "AG", nameEn: "Antigua and Barbuda", nameEs: "Antigua y Barbuda" },
  { code: "AI", nameEn: "Anguilla", nameEs: "Anguila" },
  { code: "AL", nameEn: "Albania", nameEs: "Albania" },
  { code: "AM", nameEn: "Armenia", nameEs: "Armenia" },
  { code: "AO", nameEn: "Angola", nameEs: "Angola" },
  { code: "AQ", nameEn: "Antarctica", nameEs: "Antártida" },
  { code: "AR", nameEn: "Argentina", nameEs: "Argentina" },
  { code: "AS", nameEn: "American Samoa", nameEs: "Samoa Americana" },
  { code: "AT", nameEn: "Austria", nameEs: "Austria" },
  { code: "AU", nameEn: "Australia", nameEs: "Australia" },
  { code: "AW", nameEn: "Aruba", nameEs: "Aruba" },
  { code: "AX", nameEn: "Åland Islands", nameEs: "Islas Åland" },
  { code: "AZ", nameEn: "Azerbaijan", nameEs: "Azerbaiyán" },
  {
    code: "BA",
    nameEn: "Bosnia and Herzegovina",
    nameEs: "Bosnia y Herzegovina",
  },
  { code: "BB", nameEn: "Barbados", nameEs: "Barbados" },
  { code: "BD", nameEn: "Bangladesh", nameEs: "Bangladesh" },
  { code: "BE", nameEn: "Belgium", nameEs: "Bélgica" },
  { code: "BF", nameEn: "Burkina Faso", nameEs: "Burkina Faso" },
  { code: "BG", nameEn: "Bulgaria", nameEs: "Bulgaria" },
  { code: "BH", nameEn: "Bahrain", nameEs: "Baréin" },
  { code: "BI", nameEn: "Burundi", nameEs: "Burundi" },
  { code: "BJ", nameEn: "Benin", nameEs: "Benín" },
  { code: "BL", nameEn: "Saint Barthélemy", nameEs: "San Bartolomé" },
  { code: "BM", nameEn: "Bermuda", nameEs: "Bermudas" },
  { code: "BN", nameEn: "Brunei", nameEs: "Brunéi" },
  { code: "BO", nameEn: "Bolivia", nameEs: "Bolivia" },
  { code: "BQ", nameEn: "Caribbean Netherlands", nameEs: "Caribe Neerlandés" },
  { code: "BR", nameEn: "Brazil", nameEs: "Brasil" },
  { code: "BS", nameEn: "Bahamas", nameEs: "Bahamas" },
  { code: "BT", nameEn: "Bhutan", nameEs: "Bután" },
  { code: "BV", nameEn: "Bouvet Island", nameEs: "Isla Bouvet" },
  { code: "BW", nameEn: "Botswana", nameEs: "Botsuana" },
  { code: "BY", nameEn: "Belarus", nameEs: "Bielorrusia" },
  { code: "BZ", nameEn: "Belize", nameEs: "Belice" },
  { code: "CA", nameEn: "Canada", nameEs: "Canadá" },
  { code: "CC", nameEn: "Cocos Islands", nameEs: "Islas Cocos" },
  {
    code: "CD",
    nameEn: "Democratic Republic of the Congo",
    nameEs: "República Democrática del Congo",
  },
  {
    code: "CF",
    nameEn: "Central African Republic",
    nameEs: "República Centroafricana",
  },
  {
    code: "CG",
    nameEn: "Republic of the Congo",
    nameEs: "República del Congo",
  },
  { code: "CH", nameEn: "Switzerland", nameEs: "Suiza" },
  { code: "CI", nameEn: "Ivory Coast", nameEs: "Costa de Marfil" },
  { code: "CK", nameEn: "Cook Islands", nameEs: "Islas Cook" },
  { code: "CL", nameEn: "Chile", nameEs: "Chile" },
  { code: "CM", nameEn: "Cameroon", nameEs: "Camerún" },
  { code: "CN", nameEn: "China", nameEs: "China" },
  { code: "CO", nameEn: "Colombia", nameEs: "Colombia" },
  { code: "CR", nameEn: "Costa Rica", nameEs: "Costa Rica" },
  { code: "CU", nameEn: "Cuba", nameEs: "Cuba" },
  { code: "CV", nameEn: "Cape Verde", nameEs: "Cabo Verde" },
  { code: "CW", nameEn: "Curaçao", nameEs: "Curazao" },
  { code: "CX", nameEn: "Christmas Island", nameEs: "Isla de Navidad" },
  { code: "CY", nameEn: "Cyprus", nameEs: "Chipre" },
  { code: "CZ", nameEn: "Czech Republic", nameEs: "República Checa" },
  { code: "DE", nameEn: "Germany", nameEs: "Alemania" },
  { code: "DJ", nameEn: "Djibouti", nameEs: "Yibuti" },
  { code: "DK", nameEn: "Denmark", nameEs: "Dinamarca" },
  { code: "DM", nameEn: "Dominica", nameEs: "Dominica" },
  { code: "DO", nameEn: "Dominican Republic", nameEs: "República Dominicana" },
  { code: "DZ", nameEn: "Algeria", nameEs: "Argelia" },
  { code: "EC", nameEn: "Ecuador", nameEs: "Ecuador" },
  { code: "EE", nameEn: "Estonia", nameEs: "Estonia" },
  { code: "EG", nameEn: "Egypt", nameEs: "Egipto" },
  { code: "EH", nameEn: "Western Sahara", nameEs: "Sahara Occidental" },
  { code: "ER", nameEn: "Eritrea", nameEs: "Eritrea" },
  { code: "ES", nameEn: "Spain", nameEs: "España" },
  { code: "ET", nameEn: "Ethiopia", nameEs: "Etiopía" },
  { code: "FI", nameEn: "Finland", nameEs: "Finlandia" },
  { code: "FJ", nameEn: "Fiji", nameEs: "Fiyi" },
  { code: "FK", nameEn: "Falkland Islands", nameEs: "Islas Malvinas" },
  { code: "FM", nameEn: "Micronesia", nameEs: "Micronesia" },
  { code: "FO", nameEn: "Faroe Islands", nameEs: "Islas Feroe" },
  { code: "FR", nameEn: "France", nameEs: "Francia" },
  { code: "GA", nameEn: "Gabon", nameEs: "Gabón" },
  { code: "GB", nameEn: "United Kingdom", nameEs: "Reino Unido" },
  { code: "GD", nameEn: "Grenada", nameEs: "Granada" },
  { code: "GE", nameEn: "Georgia", nameEs: "Georgia" },
  { code: "GF", nameEn: "French Guiana", nameEs: "Guayana Francesa" },
  { code: "GG", nameEn: "Guernsey", nameEs: "Guernsey" },
  { code: "GH", nameEn: "Ghana", nameEs: "Ghana" },
  { code: "GI", nameEn: "Gibraltar", nameEs: "Gibraltar" },
  { code: "GL", nameEn: "Greenland", nameEs: "Groenlandia" },
  { code: "GM", nameEn: "Gambia", nameEs: "Gambia" },
  { code: "GN", nameEn: "Guinea", nameEs: "Guinea" },
  { code: "GP", nameEn: "Guadeloupe", nameEs: "Guadalupe" },
  { code: "GQ", nameEn: "Equatorial Guinea", nameEs: "Guinea Ecuatorial" },
  { code: "GR", nameEn: "Greece", nameEs: "Grecia" },
  {
    code: "GS",
    nameEn: "South Georgia and South Sandwich Islands",
    nameEs: "Georgia del Sur y las Islas Sandwich del Sur",
  },
  { code: "GT", nameEn: "Guatemala", nameEs: "Guatemala" },
  { code: "GU", nameEn: "Guam", nameEs: "Guam" },
  { code: "GW", nameEn: "Guinea-Bissau", nameEs: "Guinea-Bisáu" },
  { code: "GY", nameEn: "Guyana", nameEs: "Guyana" },
  { code: "HK", nameEn: "Hong Kong", nameEs: "Hong Kong" },
  {
    code: "HM",
    nameEn: "Heard Island and McDonald Islands",
    nameEs: "Islas Heard y McDonald",
  },
  { code: "HN", nameEn: "Honduras", nameEs: "Honduras" },
  { code: "HR", nameEn: "Croatia", nameEs: "Croacia" },
  { code: "HT", nameEn: "Haiti", nameEs: "Haití" },
  { code: "HU", nameEn: "Hungary", nameEs: "Hungría" },
  { code: "ID", nameEn: "Indonesia", nameEs: "Indonesia" },
  { code: "IE", nameEn: "Ireland", nameEs: "Irlanda" },
  { code: "IL", nameEn: "Israel", nameEs: "Israel" },
  { code: "IM", nameEn: "Isle of Man", nameEs: "Isla de Man" },
  { code: "IN", nameEn: "India", nameEs: "India" },
  {
    code: "IO",
    nameEn: "British Indian Ocean Territory",
    nameEs: "Territorio Británico del Océano Índico",
  },
  { code: "IQ", nameEn: "Iraq", nameEs: "Irak" },
  { code: "IR", nameEn: "Iran", nameEs: "Irán" },
  { code: "IS", nameEn: "Iceland", nameEs: "Islandia" },
  { code: "IT", nameEn: "Italy", nameEs: "Italia" },
  { code: "JE", nameEn: "Jersey", nameEs: "Jersey" },
  { code: "JM", nameEn: "Jamaica", nameEs: "Jamaica" },
  { code: "JO", nameEn: "Jordan", nameEs: "Jordania" },
  { code: "JP", nameEn: "Japan", nameEs: "Japón" },
  { code: "KE", nameEn: "Kenya", nameEs: "Kenia" },
  { code: "KG", nameEn: "Kyrgyzstan", nameEs: "Kirguistán" },
  { code: "KH", nameEn: "Cambodia", nameEs: "Camboya" },
  { code: "KI", nameEn: "Kiribati", nameEs: "Kiribati" },
  { code: "KM", nameEn: "Comoros", nameEs: "Comoras" },
  {
    code: "KN",
    nameEn: "Saint Kitts and Nevis",
    nameEs: "San Cristóbal y Nieves",
  },
  { code: "KP", nameEn: "North Korea", nameEs: "Corea del Norte" },
  { code: "KR", nameEn: "South Korea", nameEs: "Corea del Sur" },
  { code: "KW", nameEn: "Kuwait", nameEs: "Kuwait" },
  { code: "KY", nameEn: "Cayman Islands", nameEs: "Islas Caimán" },
  { code: "KZ", nameEn: "Kazakhstan", nameEs: "Kazajistán" },
  { code: "LA", nameEn: "Laos", nameEs: "Laos" },
  { code: "LB", nameEn: "Lebanon", nameEs: "Líbano" },
  { code: "LC", nameEn: "Saint Lucia", nameEs: "Santa Lucía" },
  { code: "LI", nameEn: "Liechtenstein", nameEs: "Liechtenstein" },
  { code: "LK", nameEn: "Sri Lanka", nameEs: "Sri Lanka" },
  { code: "LR", nameEn: "Liberia", nameEs: "Liberia" },
  { code: "LS", nameEn: "Lesotho", nameEs: "Lesoto" },
  { code: "LT", nameEn: "Lithuania", nameEs: "Lituania" },
  { code: "LU", nameEn: "Luxembourg", nameEs: "Luxemburgo" },
  { code: "LV", nameEn: "Latvia", nameEs: "Letonia" },
  { code: "LY", nameEn: "Libya", nameEs: "Libia" },
  { code: "MA", nameEn: "Morocco", nameEs: "Marruecos" },
  { code: "MC", nameEn: "Monaco", nameEs: "Mónaco" },
  { code: "MD", nameEn: "Moldova", nameEs: "Moldavia" },
  { code: "ME", nameEn: "Montenegro", nameEs: "Montenegro" },
  { code: "MF", nameEn: "Saint Martin", nameEs: "San Martín" },
  { code: "MG", nameEn: "Madagascar", nameEs: "Madagascar" },
  { code: "MH", nameEn: "Marshall Islands", nameEs: "Islas Marshall" },
  { code: "MK", nameEn: "North Macedonia", nameEs: "Macedonia del Norte" },
  { code: "ML", nameEn: "Mali", nameEs: "Malí" },
  { code: "MM", nameEn: "Myanmar", nameEs: "Myanmar" },
  { code: "MN", nameEn: "Mongolia", nameEs: "Mongolia" },
  { code: "MO", nameEn: "Macao", nameEs: "Macao" },
  {
    code: "MP",
    nameEn: "Northern Mariana Islands",
    nameEs: "Islas Marianas del Norte",
  },
  { code: "MQ", nameEn: "Martinique", nameEs: "Martinica" },
  { code: "MR", nameEn: "Mauritania", nameEs: "Mauritania" },
  { code: "MS", nameEn: "Montserrat", nameEs: "Montserrat" },
  { code: "MT", nameEn: "Malta", nameEs: "Malta" },
  { code: "MU", nameEn: "Mauritius", nameEs: "Mauricio" },
  { code: "MV", nameEn: "Maldives", nameEs: "Maldivas" },
  { code: "MW", nameEn: "Malawi", nameEs: "Malaui" },
  { code: "MX", nameEn: "Mexico", nameEs: "México" },
  { code: "MY", nameEn: "Malaysia", nameEs: "Malasia" },
  { code: "MZ", nameEn: "Mozambique", nameEs: "Mozambique" },
  { code: "NA", nameEn: "Namibia", nameEs: "Namibia" },
  { code: "NC", nameEn: "New Caledonia", nameEs: "Nueva Caledonia" },
  { code: "NE", nameEn: "Niger", nameEs: "Níger" },
  { code: "NF", nameEn: "Norfolk Island", nameEs: "Isla Norfolk" },
  { code: "NG", nameEn: "Nigeria", nameEs: "Nigeria" },
  { code: "NI", nameEn: "Nicaragua", nameEs: "Nicaragua" },
  { code: "NL", nameEn: "Netherlands", nameEs: "Países Bajos" },
  { code: "NO", nameEn: "Norway", nameEs: "Noruega" },
  { code: "NP", nameEn: "Nepal", nameEs: "Nepal" },
  { code: "NR", nameEn: "Nauru", nameEs: "Nauru" },
  { code: "NU", nameEn: "Niue", nameEs: "Niue" },
  { code: "NZ", nameEn: "New Zealand", nameEs: "Nueva Zelanda" },
  { code: "OM", nameEn: "Oman", nameEs: "Omán" },
  { code: "PA", nameEn: "Panama", nameEs: "Panamá" },
  { code: "PE", nameEn: "Peru", nameEs: "Perú" },
  { code: "PF", nameEn: "French Polynesia", nameEs: "Polinesia Francesa" },
  { code: "PG", nameEn: "Papua New Guinea", nameEs: "Papúa Nueva Guinea" },
  { code: "PH", nameEn: "Philippines", nameEs: "Filipinas" },
  { code: "PK", nameEn: "Pakistan", nameEs: "Pakistán" },
  { code: "PL", nameEn: "Poland", nameEs: "Polonia" },
  {
    code: "PM",
    nameEn: "Saint Pierre and Miquelon",
    nameEs: "San Pedro y Miquelón",
  },
  { code: "PN", nameEn: "Pitcairn Islands", nameEs: "Islas Pitcairn" },
  { code: "PR", nameEn: "Puerto Rico", nameEs: "Puerto Rico" },
  { code: "PS", nameEn: "Palestine", nameEs: "Palestina" },
  { code: "PT", nameEn: "Portugal", nameEs: "Portugal" },
  { code: "PW", nameEn: "Palau", nameEs: "Palaos" },
  { code: "PY", nameEn: "Paraguay", nameEs: "Paraguay" },
  { code: "QA", nameEn: "Qatar", nameEs: "Catar" },
  { code: "RE", nameEn: "Réunion", nameEs: "Reunión" },
  { code: "RO", nameEn: "Romania", nameEs: "Rumania" },
  { code: "RS", nameEn: "Serbia", nameEs: "Serbia" },
  { code: "RU", nameEn: "Russia", nameEs: "Rusia" },
  { code: "RW", nameEn: "Rwanda", nameEs: "Ruanda" },
  { code: "SA", nameEn: "Saudi Arabia", nameEs: "Arabia Saudita" },
  { code: "SB", nameEn: "Solomon Islands", nameEs: "Islas Salomón" },
  { code: "SC", nameEn: "Seychelles", nameEs: "Seychelles" },
  { code: "SD", nameEn: "Sudan", nameEs: "Sudán" },
  { code: "SE", nameEn: "Sweden", nameEs: "Suecia" },
  { code: "SG", nameEn: "Singapore", nameEs: "Singapur" },
  { code: "SH", nameEn: "Saint Helena", nameEs: "Santa Elena" },
  { code: "SI", nameEn: "Slovenia", nameEs: "Eslovenia" },
  {
    code: "SJ",
    nameEn: "Svalbard and Jan Mayen",
    nameEs: "Svalbard y Jan Mayen",
  },
  { code: "SK", nameEn: "Slovakia", nameEs: "Eslovaquia" },
  { code: "SL", nameEn: "Sierra Leone", nameEs: "Sierra Leona" },
  { code: "SM", nameEn: "San Marino", nameEs: "San Marino" },
  { code: "SN", nameEn: "Senegal", nameEs: "Senegal" },
  { code: "SO", nameEn: "Somalia", nameEs: "Somalia" },
  { code: "SR", nameEn: "Suriname", nameEs: "Surinam" },
  { code: "SS", nameEn: "South Sudan", nameEs: "Sudán del Sur" },
  {
    code: "ST",
    nameEn: "São Tomé and Príncipe",
    nameEs: "Santo Tomé y Príncipe",
  },
  { code: "SV", nameEn: "El Salvador", nameEs: "El Salvador" },
  { code: "SX", nameEn: "Sint Maarten", nameEs: "San Martín" },
  { code: "SY", nameEn: "Syria", nameEs: "Siria" },
  { code: "SZ", nameEn: "Eswatini", nameEs: "Esuatini" },
  {
    code: "TC",
    nameEn: "Turks and Caicos Islands",
    nameEs: "Islas Turcas y Caicos",
  },
  { code: "TD", nameEn: "Chad", nameEs: "Chad" },
  {
    code: "TF",
    nameEn: "French Southern Territories",
    nameEs: "Territorios Australes Franceses",
  },
  { code: "TG", nameEn: "Togo", nameEs: "Togo" },
  { code: "TH", nameEn: "Thailand", nameEs: "Tailandia" },
  { code: "TJ", nameEn: "Tajikistan", nameEs: "Tayikistán" },
  { code: "TK", nameEn: "Tokelau", nameEs: "Tokelau" },
  { code: "TL", nameEn: "Timor-Leste", nameEs: "Timor Oriental" },
  { code: "TM", nameEn: "Turkmenistan", nameEs: "Turkmenistán" },
  { code: "TN", nameEn: "Tunisia", nameEs: "Túnez" },
  { code: "TO", nameEn: "Tonga", nameEs: "Tonga" },
  { code: "TR", nameEn: "Turkey", nameEs: "Turquía" },
  { code: "TT", nameEn: "Trinidad and Tobago", nameEs: "Trinidad y Tobago" },
  { code: "TV", nameEn: "Tuvalu", nameEs: "Tuvalu" },
  { code: "TW", nameEn: "Taiwan", nameEs: "Taiwán" },
  { code: "TZ", nameEn: "Tanzania", nameEs: "Tanzania" },
  { code: "UA", nameEn: "Ukraine", nameEs: "Ucrania" },
  { code: "UG", nameEn: "Uganda", nameEs: "Uganda" },
  {
    code: "UM",
    nameEn: "United States Minor Outlying Islands",
    nameEs: "Islas Ultramarinas Menores de Estados Unidos",
  },
  { code: "US", nameEn: "United States", nameEs: "Estados Unidos" },
  { code: "UY", nameEn: "Uruguay", nameEs: "Uruguay" },
  { code: "UZ", nameEn: "Uzbekistan", nameEs: "Uzbekistán" },
  { code: "VA", nameEn: "Vatican City", nameEs: "Ciudad del Vaticano" },
  {
    code: "VC",
    nameEn: "Saint Vincent and the Grenadines",
    nameEs: "San Vicente y las Granadinas",
  },
  { code: "VE", nameEn: "Venezuela", nameEs: "Venezuela" },
  {
    code: "VG",
    nameEn: "British Virgin Islands",
    nameEs: "Islas Vírgenes Británicas",
  },
  {
    code: "VI",
    nameEn: "U.S. Virgin Islands",
    nameEs: "Islas Vírgenes de los Estados Unidos",
  },
  { code: "VN", nameEn: "Vietnam", nameEs: "Vietnam" },
  { code: "VU", nameEn: "Vanuatu", nameEs: "Vanuatu" },
  { code: "WF", nameEn: "Wallis and Futuna", nameEs: "Wallis y Futuna" },
  { code: "WS", nameEn: "Samoa", nameEs: "Samoa" },
  { code: "YE", nameEn: "Yemen", nameEs: "Yemen" },
  { code: "YT", nameEn: "Mayotte", nameEs: "Mayotte" },
  { code: "ZA", nameEn: "South Africa", nameEs: "Sudáfrica" },
  { code: "ZM", nameEn: "Zambia", nameEs: "Zambia" },
  { code: "ZW", nameEn: "Zimbabwe", nameEs: "Zimbabue" },
];

// Helper function to get country codes
export const countryCodesSet: Set<string> = new Set(
  countries.map((c) => c.code)
);

// Updated function to check if a code is valid
export const isCountryCode = (code: string) => {
  return countryCodesSet.has(code);
};

// New helper functions
export const getCountryName = (code: string, language: "en" | "es") => {
  const country = countries.find((c) => c.code === code);
  if (!country) return null;
  return language === "en" ? country.nameEn : country.nameEs;
};
