interface Country {
  code: string;
  // ISO 3166-1 numeric: the key of the landing page's country shapes
  // (scripts/generate-country-shapes.mjs).
  numericCode: string;
  nameEn: string;
  nameEs: string;
}

export const countries: Country[] = [
  { code: "AD", numericCode: "020", nameEn: "Andorra", nameEs: "Andorra" },
  {
    code: "AE",
    numericCode: "784",
    nameEn: "United Arab Emirates",
    nameEs: "Emiratos Árabes Unidos",
  },
  {
    code: "AF",
    numericCode: "004",
    nameEn: "Afghanistan",
    nameEs: "Afganistán",
  },
  {
    code: "AG",
    numericCode: "028",
    nameEn: "Antigua and Barbuda",
    nameEs: "Antigua y Barbuda",
  },
  { code: "AI", numericCode: "660", nameEn: "Anguilla", nameEs: "Anguila" },
  { code: "AL", numericCode: "008", nameEn: "Albania", nameEs: "Albania" },
  { code: "AM", numericCode: "051", nameEn: "Armenia", nameEs: "Armenia" },
  { code: "AO", numericCode: "024", nameEn: "Angola", nameEs: "Angola" },
  { code: "AQ", numericCode: "010", nameEn: "Antarctica", nameEs: "Antártida" },
  { code: "AR", numericCode: "032", nameEn: "Argentina", nameEs: "Argentina" },
  {
    code: "AS",
    numericCode: "016",
    nameEn: "American Samoa",
    nameEs: "Samoa Americana",
  },
  { code: "AT", numericCode: "040", nameEn: "Austria", nameEs: "Austria" },
  { code: "AU", numericCode: "036", nameEn: "Australia", nameEs: "Australia" },
  { code: "AW", numericCode: "533", nameEn: "Aruba", nameEs: "Aruba" },
  {
    code: "AX",
    numericCode: "248",
    nameEn: "Åland Islands",
    nameEs: "Islas Åland",
  },
  {
    code: "AZ",
    numericCode: "031",
    nameEn: "Azerbaijan",
    nameEs: "Azerbaiyán",
  },
  {
    code: "BA",
    numericCode: "070",
    nameEn: "Bosnia and Herzegovina",
    nameEs: "Bosnia y Herzegovina",
  },
  { code: "BB", numericCode: "052", nameEn: "Barbados", nameEs: "Barbados" },
  {
    code: "BD",
    numericCode: "050",
    nameEn: "Bangladesh",
    nameEs: "Bangladesh",
  },
  { code: "BE", numericCode: "056", nameEn: "Belgium", nameEs: "Bélgica" },
  {
    code: "BF",
    numericCode: "854",
    nameEn: "Burkina Faso",
    nameEs: "Burkina Faso",
  },
  { code: "BG", numericCode: "100", nameEn: "Bulgaria", nameEs: "Bulgaria" },
  { code: "BH", numericCode: "048", nameEn: "Bahrain", nameEs: "Baréin" },
  { code: "BI", numericCode: "108", nameEn: "Burundi", nameEs: "Burundi" },
  { code: "BJ", numericCode: "204", nameEn: "Benin", nameEs: "Benín" },
  {
    code: "BL",
    numericCode: "652",
    nameEn: "Saint Barthélemy",
    nameEs: "San Bartolomé",
  },
  { code: "BM", numericCode: "060", nameEn: "Bermuda", nameEs: "Bermudas" },
  { code: "BN", numericCode: "096", nameEn: "Brunei", nameEs: "Brunéi" },
  { code: "BO", numericCode: "068", nameEn: "Bolivia", nameEs: "Bolivia" },
  {
    code: "BQ",
    numericCode: "535",
    nameEn: "Caribbean Netherlands",
    nameEs: "Caribe Neerlandés",
  },
  { code: "BR", numericCode: "076", nameEn: "Brazil", nameEs: "Brasil" },
  { code: "BS", numericCode: "044", nameEn: "Bahamas", nameEs: "Bahamas" },
  { code: "BT", numericCode: "064", nameEn: "Bhutan", nameEs: "Bután" },
  {
    code: "BV",
    numericCode: "074",
    nameEn: "Bouvet Island",
    nameEs: "Isla Bouvet",
  },
  { code: "BW", numericCode: "072", nameEn: "Botswana", nameEs: "Botsuana" },
  { code: "BY", numericCode: "112", nameEn: "Belarus", nameEs: "Bielorrusia" },
  { code: "BZ", numericCode: "084", nameEn: "Belize", nameEs: "Belice" },
  { code: "CA", numericCode: "124", nameEn: "Canada", nameEs: "Canadá" },
  {
    code: "CC",
    numericCode: "166",
    nameEn: "Cocos Islands",
    nameEs: "Islas Cocos",
  },
  {
    code: "CD",
    numericCode: "180",
    nameEn: "Democratic Republic of the Congo",
    nameEs: "República Democrática del Congo",
  },
  {
    code: "CF",
    numericCode: "140",
    nameEn: "Central African Republic",
    nameEs: "República Centroafricana",
  },
  {
    code: "CG",
    numericCode: "178",
    nameEn: "Republic of the Congo",
    nameEs: "República del Congo",
  },
  { code: "CH", numericCode: "756", nameEn: "Switzerland", nameEs: "Suiza" },
  {
    code: "CI",
    numericCode: "384",
    nameEn: "Ivory Coast",
    nameEs: "Costa de Marfil",
  },
  {
    code: "CK",
    numericCode: "184",
    nameEn: "Cook Islands",
    nameEs: "Islas Cook",
  },
  { code: "CL", numericCode: "152", nameEn: "Chile", nameEs: "Chile" },
  { code: "CM", numericCode: "120", nameEn: "Cameroon", nameEs: "Camerún" },
  { code: "CN", numericCode: "156", nameEn: "China", nameEs: "China" },
  { code: "CO", numericCode: "170", nameEn: "Colombia", nameEs: "Colombia" },
  {
    code: "CR",
    numericCode: "188",
    nameEn: "Costa Rica",
    nameEs: "Costa Rica",
  },
  { code: "CU", numericCode: "192", nameEn: "Cuba", nameEs: "Cuba" },
  {
    code: "CV",
    numericCode: "132",
    nameEn: "Cape Verde",
    nameEs: "Cabo Verde",
  },
  { code: "CW", numericCode: "531", nameEn: "Curaçao", nameEs: "Curazao" },
  {
    code: "CX",
    numericCode: "162",
    nameEn: "Christmas Island",
    nameEs: "Isla de Navidad",
  },
  { code: "CY", numericCode: "196", nameEn: "Cyprus", nameEs: "Chipre" },
  {
    code: "CZ",
    numericCode: "203",
    nameEn: "Czech Republic",
    nameEs: "República Checa",
  },
  { code: "DE", numericCode: "276", nameEn: "Germany", nameEs: "Alemania" },
  { code: "DJ", numericCode: "262", nameEn: "Djibouti", nameEs: "Yibuti" },
  { code: "DK", numericCode: "208", nameEn: "Denmark", nameEs: "Dinamarca" },
  { code: "DM", numericCode: "212", nameEn: "Dominica", nameEs: "Dominica" },
  {
    code: "DO",
    numericCode: "214",
    nameEn: "Dominican Republic",
    nameEs: "República Dominicana",
  },
  { code: "DZ", numericCode: "012", nameEn: "Algeria", nameEs: "Argelia" },
  { code: "EC", numericCode: "218", nameEn: "Ecuador", nameEs: "Ecuador" },
  { code: "EE", numericCode: "233", nameEn: "Estonia", nameEs: "Estonia" },
  { code: "EG", numericCode: "818", nameEn: "Egypt", nameEs: "Egipto" },
  {
    code: "EH",
    numericCode: "732",
    nameEn: "Western Sahara",
    nameEs: "Sahara Occidental",
  },
  { code: "ER", numericCode: "232", nameEn: "Eritrea", nameEs: "Eritrea" },
  { code: "ES", numericCode: "724", nameEn: "Spain", nameEs: "España" },
  { code: "ET", numericCode: "231", nameEn: "Ethiopia", nameEs: "Etiopía" },
  { code: "FI", numericCode: "246", nameEn: "Finland", nameEs: "Finlandia" },
  { code: "FJ", numericCode: "242", nameEn: "Fiji", nameEs: "Fiyi" },
  {
    code: "FK",
    numericCode: "238",
    nameEn: "Falkland Islands",
    nameEs: "Islas Malvinas",
  },
  {
    code: "FM",
    numericCode: "583",
    nameEn: "Micronesia",
    nameEs: "Micronesia",
  },
  {
    code: "FO",
    numericCode: "234",
    nameEn: "Faroe Islands",
    nameEs: "Islas Feroe",
  },
  { code: "FR", numericCode: "250", nameEn: "France", nameEs: "Francia" },
  { code: "GA", numericCode: "266", nameEn: "Gabon", nameEs: "Gabón" },
  {
    code: "GB",
    numericCode: "826",
    nameEn: "United Kingdom",
    nameEs: "Reino Unido",
  },
  { code: "GD", numericCode: "308", nameEn: "Grenada", nameEs: "Granada" },
  { code: "GE", numericCode: "268", nameEn: "Georgia", nameEs: "Georgia" },
  {
    code: "GF",
    numericCode: "254",
    nameEn: "French Guiana",
    nameEs: "Guayana Francesa",
  },
  { code: "GG", numericCode: "831", nameEn: "Guernsey", nameEs: "Guernsey" },
  { code: "GH", numericCode: "288", nameEn: "Ghana", nameEs: "Ghana" },
  { code: "GI", numericCode: "292", nameEn: "Gibraltar", nameEs: "Gibraltar" },
  {
    code: "GL",
    numericCode: "304",
    nameEn: "Greenland",
    nameEs: "Groenlandia",
  },
  { code: "GM", numericCode: "270", nameEn: "Gambia", nameEs: "Gambia" },
  { code: "GN", numericCode: "324", nameEn: "Guinea", nameEs: "Guinea" },
  { code: "GP", numericCode: "312", nameEn: "Guadeloupe", nameEs: "Guadalupe" },
  {
    code: "GQ",
    numericCode: "226",
    nameEn: "Equatorial Guinea",
    nameEs: "Guinea Ecuatorial",
  },
  { code: "GR", numericCode: "300", nameEn: "Greece", nameEs: "Grecia" },
  {
    code: "GS",
    numericCode: "239",
    nameEn: "South Georgia and South Sandwich Islands",
    nameEs: "Georgia del Sur y las Islas Sandwich del Sur",
  },
  { code: "GT", numericCode: "320", nameEn: "Guatemala", nameEs: "Guatemala" },
  { code: "GU", numericCode: "316", nameEn: "Guam", nameEs: "Guam" },
  {
    code: "GW",
    numericCode: "624",
    nameEn: "Guinea-Bissau",
    nameEs: "Guinea-Bisáu",
  },
  { code: "GY", numericCode: "328", nameEn: "Guyana", nameEs: "Guyana" },
  { code: "HK", numericCode: "344", nameEn: "Hong Kong", nameEs: "Hong Kong" },
  {
    code: "HM",
    numericCode: "334",
    nameEn: "Heard Island and McDonald Islands",
    nameEs: "Islas Heard y McDonald",
  },
  { code: "HN", numericCode: "340", nameEn: "Honduras", nameEs: "Honduras" },
  { code: "HR", numericCode: "191", nameEn: "Croatia", nameEs: "Croacia" },
  { code: "HT", numericCode: "332", nameEn: "Haiti", nameEs: "Haití" },
  { code: "HU", numericCode: "348", nameEn: "Hungary", nameEs: "Hungría" },
  { code: "ID", numericCode: "360", nameEn: "Indonesia", nameEs: "Indonesia" },
  { code: "IE", numericCode: "372", nameEn: "Ireland", nameEs: "Irlanda" },
  { code: "IL", numericCode: "376", nameEn: "Israel", nameEs: "Israel" },
  {
    code: "IM",
    numericCode: "833",
    nameEn: "Isle of Man",
    nameEs: "Isla de Man",
  },
  { code: "IN", numericCode: "356", nameEn: "India", nameEs: "India" },
  {
    code: "IO",
    numericCode: "086",
    nameEn: "British Indian Ocean Territory",
    nameEs: "Territorio Británico del Océano Índico",
  },
  { code: "IQ", numericCode: "368", nameEn: "Iraq", nameEs: "Irak" },
  { code: "IR", numericCode: "364", nameEn: "Iran", nameEs: "Irán" },
  { code: "IS", numericCode: "352", nameEn: "Iceland", nameEs: "Islandia" },
  { code: "IT", numericCode: "380", nameEn: "Italy", nameEs: "Italia" },
  { code: "JE", numericCode: "832", nameEn: "Jersey", nameEs: "Jersey" },
  { code: "JM", numericCode: "388", nameEn: "Jamaica", nameEs: "Jamaica" },
  { code: "JO", numericCode: "400", nameEn: "Jordan", nameEs: "Jordania" },
  { code: "JP", numericCode: "392", nameEn: "Japan", nameEs: "Japón" },
  { code: "KE", numericCode: "404", nameEn: "Kenya", nameEs: "Kenia" },
  {
    code: "KG",
    numericCode: "417",
    nameEn: "Kyrgyzstan",
    nameEs: "Kirguistán",
  },
  { code: "KH", numericCode: "116", nameEn: "Cambodia", nameEs: "Camboya" },
  { code: "KI", numericCode: "296", nameEn: "Kiribati", nameEs: "Kiribati" },
  { code: "KM", numericCode: "174", nameEn: "Comoros", nameEs: "Comoras" },
  {
    code: "KN",
    numericCode: "659",
    nameEn: "Saint Kitts and Nevis",
    nameEs: "San Cristóbal y Nieves",
  },
  {
    code: "KP",
    numericCode: "408",
    nameEn: "North Korea",
    nameEs: "Corea del Norte",
  },
  {
    code: "KR",
    numericCode: "410",
    nameEn: "South Korea",
    nameEs: "Corea del Sur",
  },
  { code: "KW", numericCode: "414", nameEn: "Kuwait", nameEs: "Kuwait" },
  {
    code: "KY",
    numericCode: "136",
    nameEn: "Cayman Islands",
    nameEs: "Islas Caimán",
  },
  {
    code: "KZ",
    numericCode: "398",
    nameEn: "Kazakhstan",
    nameEs: "Kazajistán",
  },
  { code: "LA", numericCode: "418", nameEn: "Laos", nameEs: "Laos" },
  { code: "LB", numericCode: "422", nameEn: "Lebanon", nameEs: "Líbano" },
  {
    code: "LC",
    numericCode: "662",
    nameEn: "Saint Lucia",
    nameEs: "Santa Lucía",
  },
  {
    code: "LI",
    numericCode: "438",
    nameEn: "Liechtenstein",
    nameEs: "Liechtenstein",
  },
  { code: "LK", numericCode: "144", nameEn: "Sri Lanka", nameEs: "Sri Lanka" },
  { code: "LR", numericCode: "430", nameEn: "Liberia", nameEs: "Liberia" },
  { code: "LS", numericCode: "426", nameEn: "Lesotho", nameEs: "Lesoto" },
  { code: "LT", numericCode: "440", nameEn: "Lithuania", nameEs: "Lituania" },
  {
    code: "LU",
    numericCode: "442",
    nameEn: "Luxembourg",
    nameEs: "Luxemburgo",
  },
  { code: "LV", numericCode: "428", nameEn: "Latvia", nameEs: "Letonia" },
  { code: "LY", numericCode: "434", nameEn: "Libya", nameEs: "Libia" },
  { code: "MA", numericCode: "504", nameEn: "Morocco", nameEs: "Marruecos" },
  { code: "MC", numericCode: "492", nameEn: "Monaco", nameEs: "Mónaco" },
  { code: "MD", numericCode: "498", nameEn: "Moldova", nameEs: "Moldavia" },
  {
    code: "ME",
    numericCode: "499",
    nameEn: "Montenegro",
    nameEs: "Montenegro",
  },
  {
    code: "MF",
    numericCode: "663",
    nameEn: "Saint Martin",
    nameEs: "San Martín",
  },
  {
    code: "MG",
    numericCode: "450",
    nameEn: "Madagascar",
    nameEs: "Madagascar",
  },
  {
    code: "MH",
    numericCode: "584",
    nameEn: "Marshall Islands",
    nameEs: "Islas Marshall",
  },
  {
    code: "MK",
    numericCode: "807",
    nameEn: "North Macedonia",
    nameEs: "Macedonia del Norte",
  },
  { code: "ML", numericCode: "466", nameEn: "Mali", nameEs: "Malí" },
  { code: "MM", numericCode: "104", nameEn: "Myanmar", nameEs: "Myanmar" },
  { code: "MN", numericCode: "496", nameEn: "Mongolia", nameEs: "Mongolia" },
  { code: "MO", numericCode: "446", nameEn: "Macao", nameEs: "Macao" },
  {
    code: "MP",
    numericCode: "580",
    nameEn: "Northern Mariana Islands",
    nameEs: "Islas Marianas del Norte",
  },
  { code: "MQ", numericCode: "474", nameEn: "Martinique", nameEs: "Martinica" },
  {
    code: "MR",
    numericCode: "478",
    nameEn: "Mauritania",
    nameEs: "Mauritania",
  },
  {
    code: "MS",
    numericCode: "500",
    nameEn: "Montserrat",
    nameEs: "Montserrat",
  },
  { code: "MT", numericCode: "470", nameEn: "Malta", nameEs: "Malta" },
  { code: "MU", numericCode: "480", nameEn: "Mauritius", nameEs: "Mauricio" },
  { code: "MV", numericCode: "462", nameEn: "Maldives", nameEs: "Maldivas" },
  { code: "MW", numericCode: "454", nameEn: "Malawi", nameEs: "Malaui" },
  { code: "MX", numericCode: "484", nameEn: "Mexico", nameEs: "México" },
  { code: "MY", numericCode: "458", nameEn: "Malaysia", nameEs: "Malasia" },
  {
    code: "MZ",
    numericCode: "508",
    nameEn: "Mozambique",
    nameEs: "Mozambique",
  },
  { code: "NA", numericCode: "516", nameEn: "Namibia", nameEs: "Namibia" },
  {
    code: "NC",
    numericCode: "540",
    nameEn: "New Caledonia",
    nameEs: "Nueva Caledonia",
  },
  { code: "NE", numericCode: "562", nameEn: "Niger", nameEs: "Níger" },
  {
    code: "NF",
    numericCode: "574",
    nameEn: "Norfolk Island",
    nameEs: "Isla Norfolk",
  },
  { code: "NG", numericCode: "566", nameEn: "Nigeria", nameEs: "Nigeria" },
  { code: "NI", numericCode: "558", nameEn: "Nicaragua", nameEs: "Nicaragua" },
  {
    code: "NL",
    numericCode: "528",
    nameEn: "Netherlands",
    nameEs: "Países Bajos",
  },
  { code: "NO", numericCode: "578", nameEn: "Norway", nameEs: "Noruega" },
  { code: "NP", numericCode: "524", nameEn: "Nepal", nameEs: "Nepal" },
  { code: "NR", numericCode: "520", nameEn: "Nauru", nameEs: "Nauru" },
  { code: "NU", numericCode: "570", nameEn: "Niue", nameEs: "Niue" },
  {
    code: "NZ",
    numericCode: "554",
    nameEn: "New Zealand",
    nameEs: "Nueva Zelanda",
  },
  { code: "OM", numericCode: "512", nameEn: "Oman", nameEs: "Omán" },
  { code: "PA", numericCode: "591", nameEn: "Panama", nameEs: "Panamá" },
  { code: "PE", numericCode: "604", nameEn: "Peru", nameEs: "Perú" },
  {
    code: "PF",
    numericCode: "258",
    nameEn: "French Polynesia",
    nameEs: "Polinesia Francesa",
  },
  {
    code: "PG",
    numericCode: "598",
    nameEn: "Papua New Guinea",
    nameEs: "Papúa Nueva Guinea",
  },
  {
    code: "PH",
    numericCode: "608",
    nameEn: "Philippines",
    nameEs: "Filipinas",
  },
  { code: "PK", numericCode: "586", nameEn: "Pakistan", nameEs: "Pakistán" },
  { code: "PL", numericCode: "616", nameEn: "Poland", nameEs: "Polonia" },
  {
    code: "PM",
    numericCode: "666",
    nameEn: "Saint Pierre and Miquelon",
    nameEs: "San Pedro y Miquelón",
  },
  {
    code: "PN",
    numericCode: "612",
    nameEn: "Pitcairn Islands",
    nameEs: "Islas Pitcairn",
  },
  {
    code: "PR",
    numericCode: "630",
    nameEn: "Puerto Rico",
    nameEs: "Puerto Rico",
  },
  { code: "PS", numericCode: "275", nameEn: "Palestine", nameEs: "Palestina" },
  { code: "PT", numericCode: "620", nameEn: "Portugal", nameEs: "Portugal" },
  { code: "PW", numericCode: "585", nameEn: "Palau", nameEs: "Palaos" },
  { code: "PY", numericCode: "600", nameEn: "Paraguay", nameEs: "Paraguay" },
  { code: "QA", numericCode: "634", nameEn: "Qatar", nameEs: "Catar" },
  { code: "RE", numericCode: "638", nameEn: "Réunion", nameEs: "Reunión" },
  { code: "RO", numericCode: "642", nameEn: "Romania", nameEs: "Rumania" },
  { code: "RS", numericCode: "688", nameEn: "Serbia", nameEs: "Serbia" },
  { code: "RU", numericCode: "643", nameEn: "Russia", nameEs: "Rusia" },
  { code: "RW", numericCode: "646", nameEn: "Rwanda", nameEs: "Ruanda" },
  {
    code: "SA",
    numericCode: "682",
    nameEn: "Saudi Arabia",
    nameEs: "Arabia Saudita",
  },
  {
    code: "SB",
    numericCode: "090",
    nameEn: "Solomon Islands",
    nameEs: "Islas Salomón",
  },
  {
    code: "SC",
    numericCode: "690",
    nameEn: "Seychelles",
    nameEs: "Seychelles",
  },
  { code: "SD", numericCode: "729", nameEn: "Sudan", nameEs: "Sudán" },
  { code: "SE", numericCode: "752", nameEn: "Sweden", nameEs: "Suecia" },
  { code: "SG", numericCode: "702", nameEn: "Singapore", nameEs: "Singapur" },
  {
    code: "SH",
    numericCode: "654",
    nameEn: "Saint Helena",
    nameEs: "Santa Elena",
  },
  { code: "SI", numericCode: "705", nameEn: "Slovenia", nameEs: "Eslovenia" },
  {
    code: "SJ",
    numericCode: "744",
    nameEn: "Svalbard and Jan Mayen",
    nameEs: "Svalbard y Jan Mayen",
  },
  { code: "SK", numericCode: "703", nameEn: "Slovakia", nameEs: "Eslovaquia" },
  {
    code: "SL",
    numericCode: "694",
    nameEn: "Sierra Leone",
    nameEs: "Sierra Leona",
  },
  {
    code: "SM",
    numericCode: "674",
    nameEn: "San Marino",
    nameEs: "San Marino",
  },
  { code: "SN", numericCode: "686", nameEn: "Senegal", nameEs: "Senegal" },
  { code: "SO", numericCode: "706", nameEn: "Somalia", nameEs: "Somalia" },
  { code: "SR", numericCode: "740", nameEn: "Suriname", nameEs: "Surinam" },
  {
    code: "SS",
    numericCode: "728",
    nameEn: "South Sudan",
    nameEs: "Sudán del Sur",
  },
  {
    code: "ST",
    numericCode: "678",
    nameEn: "São Tomé and Príncipe",
    nameEs: "Santo Tomé y Príncipe",
  },
  {
    code: "SV",
    numericCode: "222",
    nameEn: "El Salvador",
    nameEs: "El Salvador",
  },
  {
    code: "SX",
    numericCode: "534",
    nameEn: "Sint Maarten",
    nameEs: "San Martín",
  },
  { code: "SY", numericCode: "760", nameEn: "Syria", nameEs: "Siria" },
  { code: "SZ", numericCode: "748", nameEn: "Eswatini", nameEs: "Esuatini" },
  {
    code: "TC",
    numericCode: "796",
    nameEn: "Turks and Caicos Islands",
    nameEs: "Islas Turcas y Caicos",
  },
  { code: "TD", numericCode: "148", nameEn: "Chad", nameEs: "Chad" },
  {
    code: "TF",
    numericCode: "260",
    nameEn: "French Southern Territories",
    nameEs: "Territorios Australes Franceses",
  },
  { code: "TG", numericCode: "768", nameEn: "Togo", nameEs: "Togo" },
  { code: "TH", numericCode: "764", nameEn: "Thailand", nameEs: "Tailandia" },
  {
    code: "TJ",
    numericCode: "762",
    nameEn: "Tajikistan",
    nameEs: "Tayikistán",
  },
  { code: "TK", numericCode: "772", nameEn: "Tokelau", nameEs: "Tokelau" },
  {
    code: "TL",
    numericCode: "626",
    nameEn: "Timor-Leste",
    nameEs: "Timor Oriental",
  },
  {
    code: "TM",
    numericCode: "795",
    nameEn: "Turkmenistan",
    nameEs: "Turkmenistán",
  },
  { code: "TN", numericCode: "788", nameEn: "Tunisia", nameEs: "Túnez" },
  { code: "TO", numericCode: "776", nameEn: "Tonga", nameEs: "Tonga" },
  { code: "TR", numericCode: "792", nameEn: "Turkey", nameEs: "Turquía" },
  {
    code: "TT",
    numericCode: "780",
    nameEn: "Trinidad and Tobago",
    nameEs: "Trinidad y Tobago",
  },
  { code: "TV", numericCode: "798", nameEn: "Tuvalu", nameEs: "Tuvalu" },
  { code: "TW", numericCode: "158", nameEn: "Taiwan", nameEs: "Taiwán" },
  { code: "TZ", numericCode: "834", nameEn: "Tanzania", nameEs: "Tanzania" },
  { code: "UA", numericCode: "804", nameEn: "Ukraine", nameEs: "Ucrania" },
  { code: "UG", numericCode: "800", nameEn: "Uganda", nameEs: "Uganda" },
  {
    code: "UM",
    numericCode: "581",
    nameEn: "United States Minor Outlying Islands",
    nameEs: "Islas Ultramarinas Menores de Estados Unidos",
  },
  {
    code: "US",
    numericCode: "840",
    nameEn: "United States",
    nameEs: "Estados Unidos",
  },
  { code: "UY", numericCode: "858", nameEn: "Uruguay", nameEs: "Uruguay" },
  {
    code: "UZ",
    numericCode: "860",
    nameEn: "Uzbekistan",
    nameEs: "Uzbekistán",
  },
  {
    code: "VA",
    numericCode: "336",
    nameEn: "Vatican City",
    nameEs: "Ciudad del Vaticano",
  },
  {
    code: "VC",
    numericCode: "670",
    nameEn: "Saint Vincent and the Grenadines",
    nameEs: "San Vicente y las Granadinas",
  },
  { code: "VE", numericCode: "862", nameEn: "Venezuela", nameEs: "Venezuela" },
  {
    code: "VG",
    numericCode: "092",
    nameEn: "British Virgin Islands",
    nameEs: "Islas Vírgenes Británicas",
  },
  {
    code: "VI",
    numericCode: "850",
    nameEn: "U.S. Virgin Islands",
    nameEs: "Islas Vírgenes de los Estados Unidos",
  },
  { code: "VN", numericCode: "704", nameEn: "Vietnam", nameEs: "Vietnam" },
  { code: "VU", numericCode: "548", nameEn: "Vanuatu", nameEs: "Vanuatu" },
  {
    code: "WF",
    numericCode: "876",
    nameEn: "Wallis and Futuna",
    nameEs: "Wallis y Futuna",
  },
  { code: "WS", numericCode: "882", nameEn: "Samoa", nameEs: "Samoa" },
  { code: "YE", numericCode: "887", nameEn: "Yemen", nameEs: "Yemen" },
  { code: "YT", numericCode: "175", nameEn: "Mayotte", nameEs: "Mayotte" },
  {
    code: "ZA",
    numericCode: "710",
    nameEn: "South Africa",
    nameEs: "Sudáfrica",
  },
  { code: "ZM", numericCode: "894", nameEn: "Zambia", nameEs: "Zambia" },
  { code: "ZW", numericCode: "716", nameEn: "Zimbabwe", nameEs: "Zimbabue" },
];

// New helper functions
export const getCountryName = (code: string, language: "en" | "es") => {
  const country = countries.find((c) => c.code === code);
  if (!country) return null;
  return language === "en" ? country.nameEn : country.nameEs;
};
